"""Initial Migration

Revision ID: cdd2e055fcf5
Revises: 
Create Date: 2025-06-25 12:10:35.482599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd2e055fcf5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('capsules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('media_url', sa.String(length=255), nullable=True),
    sa.Column('unlock_date', sa.DateTime(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_capsules_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('capsules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capsules_unlock_date'), ['unlock_date'], unique=False)

    op.create_table('email_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capsule_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['capsule_id'], ['capsules.id'], name=op.f('fk_email_reminders_capsule_id_capsules')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capsule_id')
    )
    with op.batch_alter_table('email_reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_reminders_scheduled_for'), ['scheduled_for'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_reminders_scheduled_for'))

    op.drop_table('email_reminders')
    with op.batch_alter_table('capsules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capsules_unlock_date'))

    op.drop_table('capsules')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    # ### end Alembic commands ###
